# Generated by Django 6.0.3 on 2026-04-04 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название отделения')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код доступа')),
                ('specialty', models.CharField(blank=True, max_length=100, verbose_name='Специальность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('departments', models.ManyToManyField(blank=True, to='hospital.department', verbose_name='Отделения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Учетная запись')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='DischargeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200, verbose_name='ФИО пациента')),
                ('department', models.CharField(max_length=100, verbose_name='Отделение')),
                ('room_number', models.IntegerField(verbose_name='Номер палаты')),
                ('date_admitted', models.DateField(verbose_name='Дата поступления')),
                ('date_discharged', models.DateField(auto_now_add=True, verbose_name='Дата выписки')),
                ('disease', models.TextField(verbose_name='Диагноз/Причина выписки')),
                ('discharged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.doctor', verbose_name='Выписавший врач')),
            ],
            options={
                'verbose_name': 'История выписки',
                'verbose_name_plural': 'Истории выписок',
                'ordering': ['-date_discharged'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер палаты')),
                ('capacity', models.IntegerField(default=4, verbose_name='Вместимость')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.department', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Палата',
                'verbose_name_plural': 'Палаты',
                'ordering': ['department', 'number'],
                'unique_together': {('department', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('allergy', models.TextField(blank=True, verbose_name='Аллергия')),
                ('age_category', models.CharField(blank=True, max_length=20, verbose_name='Возрастная категория')),
                ('admission_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления')),
                ('admitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.doctor', verbose_name='Врач, принявший пациента')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.department', verbose_name='Отделение')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.room', verbose_name='Палата')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
